CREATE DATABASE IF NOT EXISTS ELEICAO;

USE ELEICAO;

CREATE TABLE LOCALIDADE(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(150) NOT NULL,
    REGIAO VARCHAR(80) NOT NULL,
    PRIMARY KEY(ID)
)ENGINE = INNODB;

CREATE TABLE ZONAS_ELEITORAIS(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    ENDERECO VARCHAR(180) NOT NULL,
    LOCALIDADE_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY(LOCALIDADE_ID) REFERENCES LOCALIDADE(ID),
    PRIMARY KEY(ID)
)ENGINE = INNODB;

CREATE TABLE SECOES(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    DESCRICAO VARCHAR(180) NOT NULL,
    ZONAS_ELEITORAIS_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY(ZONAS_ELEITORAIS_ID) REFERENCES ZONAS_ELEITORAIS(ID),
    PRIMARY KEY(ID)
)ENGINE = INNODB;

CREATE TABLE ELEITOR(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(180) NOT NULL,
    ENDERECO VARCHAR(150) NOT NULL,
    SECOES_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY(SECOES_ID) REFERENCES SECOES(ID),
	PRIMARY KEY(ID)
)ENGINE = INNODB;

CREATE TABLE CARGO(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    DESCRICAO VARCHAR(200),
    PRIMARY KEY(ID)
) ENGINE = INNODB;

CREATE TABLE VOTO(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	DATA DATE NOT NULL,
    QUANTIDADE INT UNSIGNED NOT NULL,
    ELEITOR_ID INT UNSIGNED NOT NULL ,
    CARGO_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY(ELEITOR_ID) REFERENCES ELEITOR(ID),
    FOREIGN KEY(CARGO_ID) REFERENCES CARGO(ID),
	PRIMARY KEY(ID)
)ENGINE = INNODB;

CREATE TABLE PARTIDO(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(80) NOT NULL,
    SIGLA CHAR(6) NOT NULL,
    PRIMARY KEY(ID)
) ENGINE = INNODB;

CREATE TABLE CANDIDATO(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(180) NOT NULL,
    ENDERECO VARCHAR(150) NOT NULL,
    CARGO_ID INT UNSIGNED NOT NULL,
    PARTIDO_ID INT UNSIGNED NOT NULL,
    FOREIGN KEY(CARGO_ID) REFERENCES CARGO(ID),
    FOREIGN KEY(PARTIDO_ID) REFERENCES PARTIDO(ID),
    PRIMARY KEY(ID)
) ENGINE = INNODB;
