CREATE DATABASE IF NOT EXISTS ESTOQUE;

USE ESTOQUE;

CREATE TABLE FORNECEDOR(
	CNPJ CHAR(20) NOT NULL,
    NOME VARCHAR(180) NOT NULL,
    ENDERECO VARCHAR(150) NOT NULL,
    PRIMARY KEY(CNPJ)
)ENGINE = INNODB;

CREATE TABLE CLIENTES(
	CPF CHAR(14) NOT NULL,
    NOME VARCHAR(180) NOT NULL,
    ENDERECO VARCHAR(150) NOT NULL,
	PRIMARY KEY(CPF)
)ENGINE =  INNODB;

CREATE TABLE PRODUTOS(
	CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(80) NOT NULL,
    PRECO DOUBLE(9,2) NOT NULL,
    PRIMARY KEY(CODIGO)
)ENGINE = INNODB;

CREATE TABLE ALMOXARIFADO(
	ID INT UNSIGNED AUTO_INCREMENT NOT NULL,
    NOME VARCHAR(80) NOT NULL,
	ENDERECO VARCHAR(150) NOT NULL,
    PRIMARY KEY(ID)
)ENGINE = INNODB;

CREATE TABLE COMPRAS(
	CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
    DESCRICAO VARCHAR(200) NOT NULL,
    DATA DATE NOT NULL,
    VALOR DOUBLE(9,2) NOT NULL,
    FORNECEDOR_CNPJ CHAR(20) NOT NULL,
    FOREIGN KEY(FORNECEDOR_CNPJ) REFERENCES FORNECEDOR(CNPJ),
    PRIMARY KEY(CODIGO)
) ENGINE = INNODB;

CREATE TABLE VENDAS(
	CODIGO INT UNSIGNED NOT NULL AUTO_INCREMENT,
	DESCRICAO VARCHAR(200) NOT NULL,
    DATA DATE NOT NULL,
    VALOR DOUBLE(9,2) NOT NULL,
    CLIENTES_CPF CHAR(14) NOT NULL,
    PRIMARY KEY(CODIGO),
    FOREIGN KEY(CLIENTES_CPF) REFERENCES CLIENTES(CPF)
) ENGINE = INNODB;

CREATE TABLE NOTA_FISCAL(
	NUMERO INT UNSIGNED NOT NULL AUTO_INCREMENT,
    TIPO CHAR(1) NOT NULL,
    VALOR DOUBLE(9,2) NOT NULL,
    DATA DATE NOT NULL,
    COMPRAS_CODIGO INT UNSIGNED NOT NULL,
    VENDAS_CODIGO INT UNSIGNED NOT NULL,
    FOREIGN KEY(COMPRAS_CODIGO) REFERENCES COMPRAS(CODIGO),
    FOREIGN KEY(VENDAS_CODIGO) REFERENCES VENDAS(CODIGO),
    PRIMARY KEY(NUMERO)
)ENGINE = INNODB;

CREATE TABLE ESTOQUE(
	ALMOXARIFADO_ID INT UNSIGNED NOT NULL,
    PRODUTOS_CODIGO INT UNSIGNED NOT NULL,
    DATA DATE NOT NULL,
    QUANTIDADE INT UNSIGNED NOT NULL,
    NOTA_FISCAL_NUMERO INT UNSIGNED NOT NULL,
    PRIMARY KEY(ALMOXARIFADO_ID, PRODUTOS_CODIGO),
    FOREIGN KEY(ALMOXARIFADO_ID) REFERENCES ALMOXARIFADO(ID),
    FOREIGN KEY(PRODUTOS_CODIGO) REFERENCES PRODUTOS(CODIGO),
    FOREIGN KEY(NOTA_FISCAL_NUMERO) REFERENCES NOTA_FISCAL(NUMERO)
)ENGINE = INNODB;

